### ISSUE TITLE
raw GRIFFIN events

### ISSUE THREAD

**Issue by katieannemills** [GRIFFINCollaboration/data-spy#1]
Hi folks - I'm planning on pulling together a first cut at this project (online parser of raw GRIFFIN data) hopefully around the end of next week. To proceed I need a couple examples of raw GRIFFIN data (and a link to the spec for this format) - can anyone link me anything? No need to actually serve real events right now, just looking for some static examples to build the app around - easy enough to plug a real data feed into it later.

cc @AdamGarnsworthy @SmithJK

**Comment by SmithJK** [comment]
Data format document is in the GRSISort wiki on GitHub. Difficult to link
from my phone, but if you can't find it, let me know.  How is this going to
be different than the Spectrum Viewer?

**Comment by AdamGarnsworthy** [comment]
I'll explain tomorrow. Bill we'll post a few example events for you tomorrow too.

**Comment by AdamGarnsworthy** [comment]
Event format documentation:
https://rawgit.com/wiki/GriffinCollaboration/GRSISort/technical-docs/GRIFFIN_Event_Format.pdf

**Comment by AdamGarnsworthy** [comment]
Set of events from one network transmission between the GRIF-C master and the MIDAS frontend. These are 4-byte words displayed in hex (so displayed leading with "0x" to indicate hex). Event header started 0x8 and trailers 0xe, this and everything in between is explained in the document.
[mdump.txt](https://github.com/GRIFFINCollaboration/data-spy/files/29015/mdump.txt)

**Comment by katieannemills** [comment]
Thanks!
